import type { Metadata } from "next"; // Importing the type definition for Metadata from Next.js
import { Inter } from "next/font/google"; // Importing the Inter font from Google Fonts using Next.js
import "./globals.css"; // Importing global CSS styles
import { Toaster } from "@/components/ui/toaster"; // Importing the Toaster component
import { Switch } from "@/components/ui/switch";
import { Label } from "@/components/ui/label";
import { useToast } from "@/components/ui/use-toast";
import ToastTest from "@/components/ToastTest";

const inter = Inter({ subsets: ["latin"] }); // Initializing the Inter font with the 'latin' subset

export const metadata: Metadata = {
  // Exporting metadata for the application
  title: "Create Next App", // Setting the title of the app
  description: "Generated by create next app", // Setting the description of the app
};

export default function RootLayout({
  // Defining the RootLayout component
  children, // Destructuring the children prop from the component's props
}: Readonly<{
  // Defining the type of the props
  children: React.ReactNode; // Specifying that the children prop is a React node
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}{" "}
        {/* Rendering the children passed to the RootLayout component */}
        <Toaster /> {/* Ensure Toaster is included to render toasts */}
      </body>
    </html>
  );
}
